# Project information
site_name: 'CAPESstack'
site_description: 'Official CAPES Documentation'
site_author: 'CAPESstack'
site_url: 'https://capesstack.io/'

# Repository
repo_name: 'capesstack/capes-docker'
repo_url: 'https://github.com/capesstack/capes-docker'

# Copyright
copyright: 'Copyright &copy; 2020 CAPESstack'

# Configuration
theme:
  name: 'material'
  language: 'en'
  # feature:
  #   tabs: true
  palette:
    primary: 'Black'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/logo.png'
  favicon: 'img/favicon.ico'


# Customization
extra:
  #manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/capesstack'
    - type: 'twitter'
      link: 'https://twitter.com/capesstack'

# Google Analytics
#google_analytics:
#  - '#'
#  - 'auto'

# Extensions
markdown_extensions:
 - admonition
 - codehilite:
     guess_lang: false
 - toc:
     permalink: true

# Page tree
nav:
  - Home: index.md
  - Install:
    - Requirements: install/requirements.md
    - Installation: install/installation.md
  - Configure: configure/index.md
  - Usage: 
    - Operation: usage/index.md
  - Services: 
    - Overview: services/index.md
    - Landing Page: services/landing_page/build_operate_maintain.md
    - Portainer: services/portainer/build_operate_maintain.md
    - CyberChef: services/cyberchef/build_operate_maintain.md
    - Gitea: services/gitea/build_operate_maintain.md
    - Etherpad: services/etherpad/build_operate_maintain.md
    - Rocketchat: services/rocketchat/build_operate_maintain.md
    - TheHive: services/thehive/build_operate_maintain.md
    - Cortex: services/thehive/build_operate_maintain.md
    - Mumble: services/mumble/build_operate_maintain.md
    - Kibana: services/kibana/build_operate_maintain.md
  - Reference:
    - Troubleshooting: reference/troubleshooting.md